#
# Node build stage
#
FROM node:20-alpine AS node-builder
WORKDIR /app

COPY . .
RUN cd app && npm ci && npm run build

#
# Rust Build stage
#
FROM rust:slim as rust-builder
WORKDIR /app

COPY . .

COPY --from=node-builder /app/dist /app/dist
RUN cargo build --release

#
# Runner stage
#
FROM debian:stable-slim as runner
WORKDIR /app

COPY --from=rust-builder /app/target/release/server /app/smoltable
COPY --from=node-builder /app/dist /app/dist

ENTRYPOINT ["/app/smoltable"]
