# fly.toml file generated for smoltable-1 on 2023-12-05T15:51:17+01:00

app = "smoltable-1"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
dockerfile = "Dockerfile.alpine"

[[mounts]]
source = "smoldata"
destination = "/data"
processes = ["disk"]
initial_size = "3gb"
auto_extend_size_threshold = 90
auto_extend_size_increment = "1GB"
auto_extend_size_limit = "50GB"

[env]
RUST_LOG = "debug"
PORT = "8080"
SMOLTABLE_DATA = "/data"

[[services]]
internal_port = 8080
processes = ["app"]
protocol = "tcp"
[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443
