# fly.toml app configuration file generated for smoltable-1 on 2024-01-12T14:56:54+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "smoltable-1"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "Dockerfile.alpine"

[env]
  PORT = "8080"
  RUST_LOG = "debug"
  SMOLTABLE_DATA = "/data"

[[mounts]]
  source = "smoldata"
  destination = "/data"
  initial_size = "3gb"
  processes = ["disk"]
  auto_extend_size_threshold = 90
  auto_extend_size_increment = "1GB"
  auto_extend_size_limit = "50GB"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
