name: Deploy page

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node-version:
          - 20
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm i
        working-directory: docs
      - name: Generate page
        run: pnpm build
        working-directory: docs
      - name: Deploy page
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/dist
