name: Deploy Docker (edge)

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Build and push Docker image
        run: |
          docker build . -f Dockerfile.alpine -t ghcr.io/${{ github.repository }}:alpine-edge
          docker build . -f Dockerfile.debian -t ghcr.io/${{ github.repository }}:debian-edge
          docker push ghcr.io/${{ github.repository }}:alpine-edge
          docker push ghcr.io/${{ github.repository }}:debian-edge
