name: Deploy Docker

# TODO: change to release
on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.alpine
          push: true # Will only build if this is not here
          # TODO: .latest & ghcr.io/${{ github.repository }}:${{ github.ref }}
          tags: |
            ghcr.io/${{ github.repository }}:edge
