name: CI

on:
  push:
    branches:
      - main # TODO: remove
  pull_request:
    branches:
      - "**"

env:
  CARGO_TERM_COLOR: always

jobs:
  test_stable:
    cancel-timeout-minutes: 20
    strategy:
      matrix:
        rust_version:
          - stable
          - "1.75.0" # MSRV
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        run: rustup default ${{ matrix.rust_version }}
      - name: Setup rust-fmt & clippy
        run: rustup component add rustfmt && rustup component add clippy
      - name: Set up cargo cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ runner.os }}-cargo
      - name: Build app
        run: npm i && npm run build
        working-directory: app
      - name: Build
        run: cargo build -v
      - name: Format
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy
      - name: Run tests
        run: cargo test -v -- --nocapture
